### PR TITLE
Dashna

### PR DESCRIPTION
**Pull request by Archana2424**
see updated ML i did use logistic and random forest cld project accuracy for test and train still working

### CODE REVIEW

**Comment by gaudiom4git** [comment]
Untitled.ipynb will be deleted when pull request #19 is merged with main.   
@Archana2424  -  Is your njhome_floodsummary.csv  very different from the one in main?   Maybe remove it from this commit and push later?

**Comment by Archana2424** [comment]
Mae I am out once I reach home at 7 pm will check all

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gaudiom4git** [comment]
@Archana2424  - It's no rush.  Just commenting in case there was some issues with merging your PR to main.   

I will merge my PR with main now so that the Untitled.ipynb is no longer a conflict for you.    Untitled was something started.  It's empty source.  I forgot to delete before committiing.

**Comment by c-ramos** [comment]
I can't merge on my end but I updated my local repo with the current main just in case. @Archana2424 Could you please create a new branch and do a new pull request or maybe try Mae's suggestion? Thanks!

**Review by c-ramos — APPROVED** [review]
Testing ML price drop

**Pull request merged**
